### ISSUE TITLE
failed with status code 401 Response text is : Unautenticated

### ISSUE THREAD

**Issue by gaoxu529** [readdle/app-store-server-api#8] opened 2024-01-04 04:31 UTC
我在laravel中使用改库是发生了以下情况，
```
    public function handle(ChannelArticleService $channelArticle)
    {
        $transactionId = '';
        try {
            $privateKey = file_get_contents(storage_path('SubscriptionKey.p8'));
            $api = new \Readdle\AppStoreServerAPI\AppStoreServerAPI(
                \Readdle\AppStoreServerAPI\Environment::PRODUCTION,
                config('payment.apple.iss'),
                'com.bundleid',
                config('payment.apple.kid'),
                $privateKey
            );


            $transactionHistory = $api->getTransactionHistory($transactionId, ['sort' => GetTransactionHistoryQueryParams::SORT__DESCENDING]);

            $transactions = $transactionHistory->getTransactions();
            foreach ($transactions as $transaction) {
                $this->info(json_encode($transaction));
            }

        } catch (\Readdle\AppStoreServerAPI\Exception\WrongEnvironmentException $e) {
            exit($e->getMessage());
        }
}
```
当执行这段代码时，总是报错failed with status code 401 Response text is : Unautenticated 。 
但是当我对这段代码进行debug时，却可以正常运行，而且也能得到正确的结果。

**Comment by pkotets** [comment] 2024-01-04 10:47
Excuse me, I don't speak Chinese, so probability of misunderstanding is quite high.

From what I translated: you are telling that when you are debugging this code, it works fine. I suppose that you don't touch the library, just playing with code which uses it. So, as long as you HAVE successful response (whatever environment it is) without touching the library, it means that the problem is not related to the library, but to incoming parameters or environment.

I would add some dumps to \Readdle\AppStoreServerAPI\HTTPRequest::performRequest() to see if incoming parameters are OK and would check JWT there, decoding it manually.

**Comment by pkotets** [comment] 2024-01-08 11:53
Closing this for now, feel free to reopen if you have more details.

**Closed as completed by pkotets** 2024-01-08 11:53 UTC
